a:
  url:
    - 192.168.8.106
  port: 22
  username: yangxing
  password: '123456'
  LogPath: /var/temp.log

b:
  url:
    - 99.99.189.98
    - 99.99.199.98
  port: 22
  username: readuser
  password: 123456
  LogPath: /APP/log/app.log


